name: CI

on:
  push:
    branches: [master]

jobs:
  validate:
    name: Install and validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Lint & format
        run: yarn lint
      - name: Type check
        run: yarn type-check
      - name: Unit test
        run: yarn test
      - name: E2E test
        run: yarn test:e2e

  chromatic:
    name: Deploy Storybook to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Required to retrieve git history
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Build Gatsby project
        run: yarn build
      - name: Build and deploy Storybook
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
